'------------------------------------------------------------------------------
' <auto-generated>
'     This code was generated by a tool.
'     Runtime Version:4.0.30319.17929
'
'     Changes to this file may cause incorrect behavior and will be lost if
'     the code is regenerated.
' </auto-generated>
'------------------------------------------------------------------------------

Option Strict On
Option Explicit On


Namespace ApiA
    
    <System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0"),  _
     System.ServiceModel.ServiceContractAttribute(Name:="Fedora-API-A", [Namespace]:="http://www.fedora.info/definitions/1/0/types/", ConfigurationName:="ApiA.FedoraAPIA")>  _
    Public Interface FedoraAPIA
        
        'CODEGEN: Parameter 'repositoryInfo' requires additional schema information that cannot be captured using the parameter mode. The specific attribute is 'System.Xml.Serialization.XmlElementAttribute'.
        <System.ServiceModel.OperationContractAttribute(Action:="http://www.fedora.info/definitions/1/0/api/#describeRepository", ReplyAction:="*"),  _
         System.ServiceModel.XmlSerializerFormatAttribute(SupportFaults:=true)>  _
        Function describeRepository(ByVal request As ApiA.describeRepositoryRequest) As <System.ServiceModel.MessageParameterAttribute(Name:="repositoryInfo")> ApiA.describeRepositoryResponse
        
        'CODEGEN: Parameter 'objectProfile' requires additional schema information that cannot be captured using the parameter mode. The specific attribute is 'System.Xml.Serialization.XmlElementAttribute'.
        <System.ServiceModel.OperationContractAttribute(Action:="http://www.fedora.info/definitions/1/0/api/#getObjectProfile", ReplyAction:="*"),  _
         System.ServiceModel.XmlSerializerFormatAttribute(SupportFaults:=true)>  _
        Function getObjectProfile(ByVal request As ApiA.getObjectProfileRequest) As <System.ServiceModel.MessageParameterAttribute(Name:="objectProfile")> ApiA.getObjectProfileResponse
        
        'CODEGEN: Parameter 'objectMethod' requires additional schema information that cannot be captured using the parameter mode. The specific attribute is 'System.Xml.Serialization.XmlElementAttribute'.
        <System.ServiceModel.OperationContractAttribute(Action:="http://www.fedora.info/definitions/1/0/api/#listMethods", ReplyAction:="*"),  _
         System.ServiceModel.XmlSerializerFormatAttribute(SupportFaults:=true)>  _
        Function listMethods(ByVal request As ApiA.listMethodsRequest) As <System.ServiceModel.MessageParameterAttribute(Name:="objectMethod")> ApiA.listMethodsResponse
        
        'CODEGEN: Parameter 'datastreamDef' requires additional schema information that cannot be captured using the parameter mode. The specific attribute is 'System.Xml.Serialization.XmlElementAttribute'.
        <System.ServiceModel.OperationContractAttribute(Action:="http://www.fedora.info/definitions/1/0/api/#listDatastreams", ReplyAction:="*"),  _
         System.ServiceModel.XmlSerializerFormatAttribute(SupportFaults:=true)>  _
        Function listDatastreams(ByVal request As ApiA.listDatastreamsRequest) As <System.ServiceModel.MessageParameterAttribute(Name:="datastreamDef")> ApiA.listDatastreamsResponse
        
        'CODEGEN: Parameter 'dissemination' requires additional schema information that cannot be captured using the parameter mode. The specific attribute is 'System.Xml.Serialization.XmlElementAttribute'.
        <System.ServiceModel.OperationContractAttribute(Action:="http://www.fedora.info/definitions/1/0/api/#getDatastreamDissemination", ReplyAction:="*"),  _
         System.ServiceModel.XmlSerializerFormatAttribute(SupportFaults:=true)>  _
        Function getDatastreamDissemination(ByVal request As ApiA.getDatastreamDisseminationRequest) As <System.ServiceModel.MessageParameterAttribute(Name:="dissemination")> ApiA.getDatastreamDisseminationResponse
        
        'CODEGEN: Parameter 'dissemination' requires additional schema information that cannot be captured using the parameter mode. The specific attribute is 'System.Xml.Serialization.XmlElementAttribute'.
        <System.ServiceModel.OperationContractAttribute(Action:="http://www.fedora.info/definitions/1/0/api/#getDissemination", ReplyAction:="*"),  _
         System.ServiceModel.XmlSerializerFormatAttribute(SupportFaults:=true)>  _
        Function getDissemination(ByVal request As ApiA.getDisseminationRequest) As <System.ServiceModel.MessageParameterAttribute(Name:="dissemination")> ApiA.getDisseminationResponse
        
        'CODEGEN: Parameter 'result' requires additional schema information that cannot be captured using the parameter mode. The specific attribute is 'System.Xml.Serialization.XmlElementAttribute'.
        <System.ServiceModel.OperationContractAttribute(Action:="http://www.fedora.info/definitions/1/0/api/#findObjects", ReplyAction:="*"),  _
         System.ServiceModel.XmlSerializerFormatAttribute(SupportFaults:=true)>  _
        Function findObjects(ByVal request As ApiA.findObjectsRequest) As <System.ServiceModel.MessageParameterAttribute(Name:="result")> ApiA.findObjectsResponse
        
        'CODEGEN: Parameter 'result' requires additional schema information that cannot be captured using the parameter mode. The specific attribute is 'System.Xml.Serialization.XmlElementAttribute'.
        <System.ServiceModel.OperationContractAttribute(Action:="http://www.fedora.info/definitions/1/0/api/#resumeFindObjects", ReplyAction:="*"),  _
         System.ServiceModel.XmlSerializerFormatAttribute(SupportFaults:=true)>  _
        Function resumeFindObjects(ByVal request As ApiA.resumeFindObjectsRequest) As <System.ServiceModel.MessageParameterAttribute(Name:="result")> ApiA.resumeFindObjectsResponse
        
        'CODEGEN: Parameter 'modifiedDate' requires additional schema information that cannot be captured using the parameter mode. The specific attribute is 'System.Xml.Serialization.XmlElementAttribute'.
        <System.ServiceModel.OperationContractAttribute(Action:="http://www.fedora.info/definitions/1/0/api/#getObjectHistory", ReplyAction:="*"),  _
         System.ServiceModel.XmlSerializerFormatAttribute(SupportFaults:=true)>  _
        Function getObjectHistory(ByVal request As ApiA.getObjectHistoryRequest) As <System.ServiceModel.MessageParameterAttribute(Name:="modifiedDate")> ApiA.getObjectHistoryResponse
    End Interface
    
    '''<remarks/>
    <System.CodeDom.Compiler.GeneratedCodeAttribute("System.Xml", "4.0.30319.17929"),  _
     System.SerializableAttribute(),  _
     System.Diagnostics.DebuggerStepThroughAttribute(),  _
     System.ComponentModel.DesignerCategoryAttribute("code"),  _
     System.Xml.Serialization.XmlTypeAttribute([Namespace]:="http://www.fedora.info/definitions/1/0/types/")>  _
    Partial Public Class RepositoryInfo
        Inherits Object
        Implements System.ComponentModel.INotifyPropertyChanged
        
        Private repositoryNameField As String
        
        Private repositoryVersionField As String
        
        Private repositoryBaseURLField As String
        
        Private repositoryPIDNamespaceField As String
        
        Private defaultExportFormatField As String
        
        Private oAINamespaceField As String
        
        Private adminEmailListField() As String
        
        Private samplePIDField As String
        
        Private sampleOAIIdentifierField As String
        
        Private sampleSearchURLField As String
        
        Private sampleAccessURLField As String
        
        Private sampleOAIURLField As String
        
        Private retainPIDsField() As String
        
        '''<remarks/>
        <System.Xml.Serialization.XmlElementAttribute(Form:=System.Xml.Schema.XmlSchemaForm.Unqualified, IsNullable:=true, Order:=0)>  _
        Public Property repositoryName() As String
            Get
                Return Me.repositoryNameField
            End Get
            Set
                Me.repositoryNameField = value
                Me.RaisePropertyChanged("repositoryName")
            End Set
        End Property
        
        '''<remarks/>
        <System.Xml.Serialization.XmlElementAttribute(Form:=System.Xml.Schema.XmlSchemaForm.Unqualified, IsNullable:=true, Order:=1)>  _
        Public Property repositoryVersion() As String
            Get
                Return Me.repositoryVersionField
            End Get
            Set
                Me.repositoryVersionField = value
                Me.RaisePropertyChanged("repositoryVersion")
            End Set
        End Property
        
        '''<remarks/>
        <System.Xml.Serialization.XmlElementAttribute(Form:=System.Xml.Schema.XmlSchemaForm.Unqualified, IsNullable:=true, Order:=2)>  _
        Public Property repositoryBaseURL() As String
            Get
                Return Me.repositoryBaseURLField
            End Get
            Set
                Me.repositoryBaseURLField = value
                Me.RaisePropertyChanged("repositoryBaseURL")
            End Set
        End Property
        
        '''<remarks/>
        <System.Xml.Serialization.XmlElementAttribute(Form:=System.Xml.Schema.XmlSchemaForm.Unqualified, IsNullable:=true, Order:=3)>  _
        Public Property repositoryPIDNamespace() As String
            Get
                Return Me.repositoryPIDNamespaceField
            End Get
            Set
                Me.repositoryPIDNamespaceField = value
                Me.RaisePropertyChanged("repositoryPIDNamespace")
            End Set
        End Property
        
        '''<remarks/>
        <System.Xml.Serialization.XmlElementAttribute(Form:=System.Xml.Schema.XmlSchemaForm.Unqualified, IsNullable:=true, Order:=4)>  _
        Public Property defaultExportFormat() As String
            Get
                Return Me.defaultExportFormatField
            End Get
            Set
                Me.defaultExportFormatField = value
                Me.RaisePropertyChanged("defaultExportFormat")
            End Set
        End Property
        
        '''<remarks/>
        <System.Xml.Serialization.XmlElementAttribute(Form:=System.Xml.Schema.XmlSchemaForm.Unqualified, IsNullable:=true, Order:=5)>  _
        Public Property OAINamespace() As String
            Get
                Return Me.oAINamespaceField
            End Get
            Set
                Me.oAINamespaceField = value
                Me.RaisePropertyChanged("OAINamespace")
            End Set
        End Property
        
        '''<remarks/>
        <System.Xml.Serialization.XmlArrayAttribute(Form:=System.Xml.Schema.XmlSchemaForm.Unqualified, IsNullable:=true, Order:=6),  _
         System.Xml.Serialization.XmlArrayItemAttribute("item", Form:=System.Xml.Schema.XmlSchemaForm.Unqualified, IsNullable:=false)>  _
        Public Property adminEmailList() As String()
            Get
                Return Me.adminEmailListField
            End Get
            Set
                Me.adminEmailListField = value
                Me.RaisePropertyChanged("adminEmailList")
            End Set
        End Property
        
        '''<remarks/>
        <System.Xml.Serialization.XmlElementAttribute(Form:=System.Xml.Schema.XmlSchemaForm.Unqualified, IsNullable:=true, Order:=7)>  _
        Public Property samplePID() As String
            Get
                Return Me.samplePIDField
            End Get
            Set
                Me.samplePIDField = value
                Me.RaisePropertyChanged("samplePID")
            End Set
        End Property
        
        '''<remarks/>
        <System.Xml.Serialization.XmlElementAttribute(Form:=System.Xml.Schema.XmlSchemaForm.Unqualified, IsNullable:=true, Order:=8)>  _
        Public Property sampleOAIIdentifier() As String
            Get
                Return Me.sampleOAIIdentifierField
            End Get
            Set
                Me.sampleOAIIdentifierField = value
                Me.RaisePropertyChanged("sampleOAIIdentifier")
            End Set
        End Property
        
        '''<remarks/>
        <System.Xml.Serialization.XmlElementAttribute(Form:=System.Xml.Schema.XmlSchemaForm.Unqualified, IsNullable:=true, Order:=9)>  _
        Public Property sampleSearchURL() As String
            Get
                Return Me.sampleSearchURLField
            End Get
            Set
                Me.sampleSearchURLField = value
                Me.RaisePropertyChanged("sampleSearchURL")
            End Set
        End Property
        
        '''<remarks/>
        <System.Xml.Serialization.XmlElementAttribute(Form:=System.Xml.Schema.XmlSchemaForm.Unqualified, IsNullable:=true, Order:=10)>  _
        Public Property sampleAccessURL() As String
            Get
                Return Me.sampleAccessURLField
            End Get
            Set
                Me.sampleAccessURLField = value
                Me.RaisePropertyChanged("sampleAccessURL")
            End Set
        End Property
        
        '''<remarks/>
        <System.Xml.Serialization.XmlElementAttribute(Form:=System.Xml.Schema.XmlSchemaForm.Unqualified, IsNullable:=true, Order:=11)>  _
        Public Property sampleOAIURL() As String
            Get
                Return Me.sampleOAIURLField
            End Get
            Set
                Me.sampleOAIURLField = value
                Me.RaisePropertyChanged("sampleOAIURL")
            End Set
        End Property
        
        '''<remarks/>
        <System.Xml.Serialization.XmlArrayAttribute(Form:=System.Xml.Schema.XmlSchemaForm.Unqualified, IsNullable:=true, Order:=12),  _
         System.Xml.Serialization.XmlArrayItemAttribute("item", Form:=System.Xml.Schema.XmlSchemaForm.Unqualified, IsNullable:=false)>  _
        Public Property retainPIDs() As String()
            Get
                Return Me.retainPIDsField
            End Get
            Set
                Me.retainPIDsField = value
                Me.RaisePropertyChanged("retainPIDs")
            End Set
        End Property
        
        Public Event PropertyChanged As System.ComponentModel.PropertyChangedEventHandler Implements System.ComponentModel.INotifyPropertyChanged.PropertyChanged
        
        Protected Sub RaisePropertyChanged(ByVal propertyName As String)
            Dim propertyChanged As System.ComponentModel.PropertyChangedEventHandler = Me.PropertyChangedEvent
            If (Not (propertyChanged) Is Nothing) Then
                propertyChanged(Me, New System.ComponentModel.PropertyChangedEventArgs(propertyName))
            End If
        End Sub
    End Class
    
    '''<remarks/>
    <System.CodeDom.Compiler.GeneratedCodeAttribute("System.Xml", "4.0.30319.17929"),  _
     System.SerializableAttribute(),  _
     System.Diagnostics.DebuggerStepThroughAttribute(),  _
     System.ComponentModel.DesignerCategoryAttribute("code"),  _
     System.Xml.Serialization.XmlTypeAttribute([Namespace]:="http://www.fedora.info/definitions/1/0/types/")>  _
    Partial Public Class ObjectFields
        Inherits Object
        Implements System.ComponentModel.INotifyPropertyChanged
        
        Private pidField As String
        
        Private labelField As String
        
        Private stateField As String
        
        Private ownerIdField As String
        
        Private cDateField As String
        
        Private mDateField As String
        
        Private dcmDateField As String
        
        Private titleField() As String
        
        Private creatorField() As String
        
        Private subjectField() As String
        
        Private descriptionField() As String
        
        Private publisherField() As String
        
        Private contributorField() As String
        
        Private dateField() As String
        
        Private typeField() As String
        
        Private formatField() As String
        
        Private identifierField() As String
        
        Private sourceField() As String
        
        Private languageField() As String
        
        Private relationField() As String
        
        Private coverageField() As String
        
        Private rightsField() As String
        
        '''<remarks/>
        <System.Xml.Serialization.XmlElementAttribute(Form:=System.Xml.Schema.XmlSchemaForm.Unqualified, IsNullable:=true, Order:=0)>  _
        Public Property pid() As String
            Get
                Return Me.pidField
            End Get
            Set
                Me.pidField = value
                Me.RaisePropertyChanged("pid")
            End Set
        End Property
        
        '''<remarks/>
        <System.Xml.Serialization.XmlElementAttribute(Form:=System.Xml.Schema.XmlSchemaForm.Unqualified, IsNullable:=true, Order:=1)>  _
        Public Property label() As String
            Get
                Return Me.labelField
            End Get
            Set
                Me.labelField = value
                Me.RaisePropertyChanged("label")
            End Set
        End Property
        
        '''<remarks/>
        <System.Xml.Serialization.XmlElementAttribute(Form:=System.Xml.Schema.XmlSchemaForm.Unqualified, IsNullable:=true, Order:=2)>  _
        Public Property state() As String
            Get
                Return Me.stateField
            End Get
            Set
                Me.stateField = value
                Me.RaisePropertyChanged("state")
            End Set
        End Property
        
        '''<remarks/>
        <System.Xml.Serialization.XmlElementAttribute(Form:=System.Xml.Schema.XmlSchemaForm.Unqualified, IsNullable:=true, Order:=3)>  _
        Public Property ownerId() As String
            Get
                Return Me.ownerIdField
            End Get
            Set
                Me.ownerIdField = value
                Me.RaisePropertyChanged("ownerId")
            End Set
        End Property
        
        '''<remarks/>
        <System.Xml.Serialization.XmlElementAttribute(Form:=System.Xml.Schema.XmlSchemaForm.Unqualified, IsNullable:=true, Order:=4)>  _
        Public Property [cDate]() As String
            Get
                Return Me.cDateField
            End Get
            Set
                Me.cDateField = value
                Me.RaisePropertyChanged("cDate")
            End Set
        End Property
        
        '''<remarks/>
        <System.Xml.Serialization.XmlElementAttribute(Form:=System.Xml.Schema.XmlSchemaForm.Unqualified, IsNullable:=true, Order:=5)>  _
        Public Property mDate() As String
            Get
                Return Me.mDateField
            End Get
            Set
                Me.mDateField = value
                Me.RaisePropertyChanged("mDate")
            End Set
        End Property
        
        '''<remarks/>
        <System.Xml.Serialization.XmlElementAttribute(Form:=System.Xml.Schema.XmlSchemaForm.Unqualified, IsNullable:=true, Order:=6)>  _
        Public Property dcmDate() As String
            Get
                Return Me.dcmDateField
            End Get
            Set
                Me.dcmDateField = value
                Me.RaisePropertyChanged("dcmDate")
            End Set
        End Property
        
        '''<remarks/>
        <System.Xml.Serialization.XmlElementAttribute("title", Form:=System.Xml.Schema.XmlSchemaForm.Unqualified, IsNullable:=true, Order:=7)>  _
        Public Property title() As String()
            Get
                Return Me.titleField
            End Get
            Set
                Me.titleField = value
                Me.RaisePropertyChanged("title")
            End Set
        End Property
        
        '''<remarks/>
        <System.Xml.Serialization.XmlElementAttribute("creator", Form:=System.Xml.Schema.XmlSchemaForm.Unqualified, IsNullable:=true, Order:=8)>  _
        Public Property creator() As String()
            Get
                Return Me.creatorField
            End Get
            Set
                Me.creatorField = value
                Me.RaisePropertyChanged("creator")
            End Set
        End Property
        
        '''<remarks/>
        <System.Xml.Serialization.XmlElementAttribute("subject", Form:=System.Xml.Schema.XmlSchemaForm.Unqualified, IsNullable:=true, Order:=9)>  _
        Public Property subject() As String()
            Get
                Return Me.subjectField
            End Get
            Set
                Me.subjectField = value
                Me.RaisePropertyChanged("subject")
            End Set
        End Property
        
        '''<remarks/>
        <System.Xml.Serialization.XmlElementAttribute("description", Form:=System.Xml.Schema.XmlSchemaForm.Unqualified, IsNullable:=true, Order:=10)>  _
        Public Property description() As String()
            Get
                Return Me.descriptionField
            End Get
            Set
                Me.descriptionField = value
                Me.RaisePropertyChanged("description")
            End Set
        End Property
        
        '''<remarks/>
        <System.Xml.Serialization.XmlElementAttribute("publisher", Form:=System.Xml.Schema.XmlSchemaForm.Unqualified, IsNullable:=true, Order:=11)>  _
        Public Property publisher() As String()
            Get
                Return Me.publisherField
            End Get
            Set
                Me.publisherField = value
                Me.RaisePropertyChanged("publisher")
            End Set
        End Property
        
        '''<remarks/>
        <System.Xml.Serialization.XmlElementAttribute("contributor", Form:=System.Xml.Schema.XmlSchemaForm.Unqualified, IsNullable:=true, Order:=12)>  _
        Public Property contributor() As String()
            Get
                Return Me.contributorField
            End Get
            Set
                Me.contributorField = value
                Me.RaisePropertyChanged("contributor")
            End Set
        End Property
        
        '''<remarks/>
        <System.Xml.Serialization.XmlElementAttribute("date", Form:=System.Xml.Schema.XmlSchemaForm.Unqualified, IsNullable:=true, Order:=13)>  _
        Public Property [date]() As String()
            Get
                Return Me.dateField
            End Get
            Set
                Me.dateField = value
                Me.RaisePropertyChanged("date")
            End Set
        End Property
        
        '''<remarks/>
        <System.Xml.Serialization.XmlElementAttribute("type", Form:=System.Xml.Schema.XmlSchemaForm.Unqualified, IsNullable:=true, Order:=14)>  _
        Public Property type() As String()
            Get
                Return Me.typeField
            End Get
            Set
                Me.typeField = value
                Me.RaisePropertyChanged("type")
            End Set
        End Property
        
        '''<remarks/>
        <System.Xml.Serialization.XmlElementAttribute("format", Form:=System.Xml.Schema.XmlSchemaForm.Unqualified, IsNullable:=true, Order:=15)>  _
        Public Property format() As String()
            Get
                Return Me.formatField
            End Get
            Set
                Me.formatField = value
                Me.RaisePropertyChanged("format")
            End Set
        End Property
        
        '''<remarks/>
        <System.Xml.Serialization.XmlElementAttribute("identifier", Form:=System.Xml.Schema.XmlSchemaForm.Unqualified, IsNullable:=true, Order:=16)>  _
        Public Property identifier() As String()
            Get
                Return Me.identifierField
            End Get
            Set
                Me.identifierField = value
                Me.RaisePropertyChanged("identifier")
            End Set
        End Property
        
        '''<remarks/>
        <System.Xml.Serialization.XmlElementAttribute("source", Form:=System.Xml.Schema.XmlSchemaForm.Unqualified, IsNullable:=true, Order:=17)>  _
        Public Property source() As String()
            Get
                Return Me.sourceField
            End Get
            Set
                Me.sourceField = value
                Me.RaisePropertyChanged("source")
            End Set
        End Property
        
        '''<remarks/>
        <System.Xml.Serialization.XmlElementAttribute("language", Form:=System.Xml.Schema.XmlSchemaForm.Unqualified, IsNullable:=true, Order:=18)>  _
        Public Property language() As String()
            Get
                Return Me.languageField
            End Get
            Set
                Me.languageField = value
                Me.RaisePropertyChanged("language")
            End Set
        End Property
        
        '''<remarks/>
        <System.Xml.Serialization.XmlElementAttribute("relation", Form:=System.Xml.Schema.XmlSchemaForm.Unqualified, IsNullable:=true, Order:=19)>  _
        Public Property relation() As String()
            Get
                Return Me.relationField
            End Get
            Set
                Me.relationField = value
                Me.RaisePropertyChanged("relation")
            End Set
        End Property
        
        '''<remarks/>
        <System.Xml.Serialization.XmlElementAttribute("coverage", Form:=System.Xml.Schema.XmlSchemaForm.Unqualified, IsNullable:=true, Order:=20)>  _
        Public Property coverage() As String()
            Get
                Return Me.coverageField
            End Get
            Set
                Me.coverageField = value
                Me.RaisePropertyChanged("coverage")
            End Set
        End Property
        
        '''<remarks/>
        <System.Xml.Serialization.XmlElementAttribute("rights", Form:=System.Xml.Schema.XmlSchemaForm.Unqualified, IsNullable:=true, Order:=21)>  _
        Public Property rights() As String()
            Get
                Return Me.rightsField
            End Get
            Set
                Me.rightsField = value
                Me.RaisePropertyChanged("rights")
            End Set
        End Property
        
        Public Event PropertyChanged As System.ComponentModel.PropertyChangedEventHandler Implements System.ComponentModel.INotifyPropertyChanged.PropertyChanged
        
        Protected Sub RaisePropertyChanged(ByVal propertyName As String)
            Dim propertyChanged As System.ComponentModel.PropertyChangedEventHandler = Me.PropertyChangedEvent
            If (Not (propertyChanged) Is Nothing) Then
                propertyChanged(Me, New System.ComponentModel.PropertyChangedEventArgs(propertyName))
            End If
        End Sub
    End Class
    
    '''<remarks/>
    <System.CodeDom.Compiler.GeneratedCodeAttribute("System.Xml", "4.0.30319.17929"),  _
     System.SerializableAttribute(),  _
     System.Diagnostics.DebuggerStepThroughAttribute(),  _
     System.ComponentModel.DesignerCategoryAttribute("code"),  _
     System.Xml.Serialization.XmlTypeAttribute([Namespace]:="http://www.fedora.info/definitions/1/0/types/")>  _
    Partial Public Class ListSession
        Inherits Object
        Implements System.ComponentModel.INotifyPropertyChanged
        
        Private tokenField As String
        
        Private cursorField As String
        
        Private completeListSizeField As String
        
        Private expirationDateField As String
        
        '''<remarks/>
        <System.Xml.Serialization.XmlElementAttribute(Form:=System.Xml.Schema.XmlSchemaForm.Unqualified, IsNullable:=true, Order:=0)>  _
        Public Property token() As String
            Get
                Return Me.tokenField
            End Get
            Set
                Me.tokenField = value
                Me.RaisePropertyChanged("token")
            End Set
        End Property
        
        '''<remarks/>
        <System.Xml.Serialization.XmlElementAttribute(Form:=System.Xml.Schema.XmlSchemaForm.Unqualified, DataType:="nonNegativeInteger", Order:=1)>  _
        Public Property cursor() As String
            Get
                Return Me.cursorField
            End Get
            Set
                Me.cursorField = value
                Me.RaisePropertyChanged("cursor")
            End Set
        End Property
        
        '''<remarks/>
        <System.Xml.Serialization.XmlElementAttribute(Form:=System.Xml.Schema.XmlSchemaForm.Unqualified, DataType:="nonNegativeInteger", Order:=2)>  _
        Public Property completeListSize() As String
            Get
                Return Me.completeListSizeField
            End Get
            Set
                Me.completeListSizeField = value
                Me.RaisePropertyChanged("completeListSize")
            End Set
        End Property
        
        '''<remarks/>
        <System.Xml.Serialization.XmlElementAttribute(Form:=System.Xml.Schema.XmlSchemaForm.Unqualified, IsNullable:=true, Order:=3)>  _
        Public Property expirationDate() As String
            Get
                Return Me.expirationDateField
            End Get
            Set
                Me.expirationDateField = value
                Me.RaisePropertyChanged("expirationDate")
            End Set
        End Property
        
        Public Event PropertyChanged As System.ComponentModel.PropertyChangedEventHandler Implements System.ComponentModel.INotifyPropertyChanged.PropertyChanged
        
        Protected Sub RaisePropertyChanged(ByVal propertyName As String)
            Dim propertyChanged As System.ComponentModel.PropertyChangedEventHandler = Me.PropertyChangedEvent
            If (Not (propertyChanged) Is Nothing) Then
                propertyChanged(Me, New System.ComponentModel.PropertyChangedEventArgs(propertyName))
            End If
        End Sub
    End Class
    
    '''<remarks/>
    <System.CodeDom.Compiler.GeneratedCodeAttribute("System.Xml", "4.0.30319.17929"),  _
     System.SerializableAttribute(),  _
     System.Diagnostics.DebuggerStepThroughAttribute(),  _
     System.ComponentModel.DesignerCategoryAttribute("code"),  _
     System.Xml.Serialization.XmlTypeAttribute([Namespace]:="http://www.fedora.info/definitions/1/0/types/")>  _
    Partial Public Class FieldSearchResult
        Inherits Object
        Implements System.ComponentModel.INotifyPropertyChanged
        
        Private listSessionField As ListSession
        
        Private resultListField() As ObjectFields
        
        '''<remarks/>
        <System.Xml.Serialization.XmlElementAttribute(Form:=System.Xml.Schema.XmlSchemaForm.Unqualified, IsNullable:=true, Order:=0)>  _
        Public Property listSession() As ListSession
            Get
                Return Me.listSessionField
            End Get
            Set
                Me.listSessionField = value
                Me.RaisePropertyChanged("listSession")
            End Set
        End Property
        
        '''<remarks/>
        <System.Xml.Serialization.XmlArrayAttribute(Form:=System.Xml.Schema.XmlSchemaForm.Unqualified, Order:=1),  _
         System.Xml.Serialization.XmlArrayItemAttribute("objectFields", Form:=System.Xml.Schema.XmlSchemaForm.Unqualified, IsNullable:=false)>  _
        Public Property resultList() As ObjectFields()
            Get
                Return Me.resultListField
            End Get
            Set
                Me.resultListField = value
                Me.RaisePropertyChanged("resultList")
            End Set
        End Property
        
        Public Event PropertyChanged As System.ComponentModel.PropertyChangedEventHandler Implements System.ComponentModel.INotifyPropertyChanged.PropertyChanged
        
        Protected Sub RaisePropertyChanged(ByVal propertyName As String)
            Dim propertyChanged As System.ComponentModel.PropertyChangedEventHandler = Me.PropertyChangedEvent
            If (Not (propertyChanged) Is Nothing) Then
                propertyChanged(Me, New System.ComponentModel.PropertyChangedEventArgs(propertyName))
            End If
        End Sub
    End Class
    
    '''<remarks/>
    <System.CodeDom.Compiler.GeneratedCodeAttribute("System.Xml", "4.0.30319.17929"),  _
     System.SerializableAttribute(),  _
     System.Diagnostics.DebuggerStepThroughAttribute(),  _
     System.ComponentModel.DesignerCategoryAttribute("code"),  _
     System.Xml.Serialization.XmlTypeAttribute([Namespace]:="http://www.fedora.info/definitions/1/0/types/")>  _
    Partial Public Class Condition
        Inherits Object
        Implements System.ComponentModel.INotifyPropertyChanged
        
        Private propertyField As String
        
        Private operatorField As System.Nullable(Of ComparisonOperator)
        
        Private valueField As String
        
        '''<remarks/>
        <System.Xml.Serialization.XmlElementAttribute(Form:=System.Xml.Schema.XmlSchemaForm.Unqualified, IsNullable:=true, Order:=0)>  _
        Public Property [property]() As String
            Get
                Return Me.propertyField
            End Get
            Set
                Me.propertyField = value
                Me.RaisePropertyChanged("property")
            End Set
        End Property
        
        '''<remarks/>
        <System.Xml.Serialization.XmlElementAttribute(Form:=System.Xml.Schema.XmlSchemaForm.Unqualified, IsNullable:=true, Order:=1)>  _
        Public Property [operator]() As System.Nullable(Of ComparisonOperator)
            Get
                Return Me.operatorField
            End Get
            Set
                Me.operatorField = value
                Me.RaisePropertyChanged("operator")
            End Set
        End Property
        
        '''<remarks/>
        <System.Xml.Serialization.XmlElementAttribute(Form:=System.Xml.Schema.XmlSchemaForm.Unqualified, IsNullable:=true, Order:=2)>  _
        Public Property value() As String
            Get
                Return Me.valueField
            End Get
            Set
                Me.valueField = value
                Me.RaisePropertyChanged("value")
            End Set
        End Property
        
        Public Event PropertyChanged As System.ComponentModel.PropertyChangedEventHandler Implements System.ComponentModel.INotifyPropertyChanged.PropertyChanged
        
        Protected Sub RaisePropertyChanged(ByVal propertyName As String)
            Dim propertyChanged As System.ComponentModel.PropertyChangedEventHandler = Me.PropertyChangedEvent
            If (Not (propertyChanged) Is Nothing) Then
                propertyChanged(Me, New System.ComponentModel.PropertyChangedEventArgs(propertyName))
            End If
        End Sub
    End Class
    
    '''<remarks/>
    <System.CodeDom.Compiler.GeneratedCodeAttribute("System.Xml", "4.0.30319.17929"),  _
     System.SerializableAttribute(),  _
     System.Xml.Serialization.XmlTypeAttribute([Namespace]:="http://www.fedora.info/definitions/1/0/types/")>  _
    Public Enum ComparisonOperator
        
        '''<remarks/>
        has
        
        '''<remarks/>
        eq
        
        '''<remarks/>
        lt
        
        '''<remarks/>
        le
        
        '''<remarks/>
        gt
        
        '''<remarks/>
        ge
    End Enum
    
    '''<remarks/>
    <System.CodeDom.Compiler.GeneratedCodeAttribute("System.Xml", "4.0.30319.17929"),  _
     System.SerializableAttribute(),  _
     System.Diagnostics.DebuggerStepThroughAttribute(),  _
     System.ComponentModel.DesignerCategoryAttribute("code"),  _
     System.Xml.Serialization.XmlTypeAttribute([Namespace]:="http://www.fedora.info/definitions/1/0/types/")>  _
    Partial Public Class FieldSearchQuery
        Inherits Object
        Implements System.ComponentModel.INotifyPropertyChanged
        
        Private itemField As Object
        
        '''<remarks/>
        <System.Xml.Serialization.XmlElementAttribute("conditions", GetType(FieldSearchQueryConditions), Form:=System.Xml.Schema.XmlSchemaForm.Unqualified, IsNullable:=true, Order:=0),  _
         System.Xml.Serialization.XmlElementAttribute("terms", GetType(String), Form:=System.Xml.Schema.XmlSchemaForm.Unqualified, IsNullable:=true, Order:=0)>  _
        Public Property Item() As Object
            Get
                Return Me.itemField
            End Get
            Set
                Me.itemField = value
                Me.RaisePropertyChanged("Item")
            End Set
        End Property
        
        Public Event PropertyChanged As System.ComponentModel.PropertyChangedEventHandler Implements System.ComponentModel.INotifyPropertyChanged.PropertyChanged
        
        Protected Sub RaisePropertyChanged(ByVal propertyName As String)
            Dim propertyChanged As System.ComponentModel.PropertyChangedEventHandler = Me.PropertyChangedEvent
            If (Not (propertyChanged) Is Nothing) Then
                propertyChanged(Me, New System.ComponentModel.PropertyChangedEventArgs(propertyName))
            End If
        End Sub
    End Class
    
    '''<remarks/>
    <System.CodeDom.Compiler.GeneratedCodeAttribute("System.Xml", "4.0.30319.17929"),  _
     System.SerializableAttribute(),  _
     System.Diagnostics.DebuggerStepThroughAttribute(),  _
     System.ComponentModel.DesignerCategoryAttribute("code"),  _
     System.Xml.Serialization.XmlTypeAttribute(AnonymousType:=true)>  _
    Partial Public Class FieldSearchQueryConditions
        Inherits Object
        Implements System.ComponentModel.INotifyPropertyChanged
        
        Private conditionField() As Condition
        
        '''<remarks/>
        <System.Xml.Serialization.XmlElementAttribute("condition", Form:=System.Xml.Schema.XmlSchemaForm.Unqualified, Order:=0)>  _
        Public Property condition() As Condition()
            Get
                Return Me.conditionField
            End Get
            Set
                Me.conditionField = value
                Me.RaisePropertyChanged("condition")
            End Set
        End Property
        
        Public Event PropertyChanged As System.ComponentModel.PropertyChangedEventHandler Implements System.ComponentModel.INotifyPropertyChanged.PropertyChanged
        
        Protected Sub RaisePropertyChanged(ByVal propertyName As String)
            Dim propertyChanged As System.ComponentModel.PropertyChangedEventHandler = Me.PropertyChangedEvent
            If (Not (propertyChanged) Is Nothing) Then
                propertyChanged(Me, New System.ComponentModel.PropertyChangedEventArgs(propertyName))
            End If
        End Sub
    End Class
    
    '''<remarks/>
    <System.CodeDom.Compiler.GeneratedCodeAttribute("System.Xml", "4.0.30319.17929"),  _
     System.SerializableAttribute(),  _
     System.Diagnostics.DebuggerStepThroughAttribute(),  _
     System.ComponentModel.DesignerCategoryAttribute("code"),  _
     System.Xml.Serialization.XmlTypeAttribute([Namespace]:="http://www.fedora.info/definitions/1/0/types/")>  _
    Partial Public Class [Property]
        Inherits Object
        Implements System.ComponentModel.INotifyPropertyChanged
        
        Private nameField As String
        
        Private valueField As String
        
        '''<remarks/>
        <System.Xml.Serialization.XmlElementAttribute(Form:=System.Xml.Schema.XmlSchemaForm.Unqualified, Order:=0)>  _
        Public Property name() As String
            Get
                Return Me.nameField
            End Get
            Set
                Me.nameField = value
                Me.RaisePropertyChanged("name")
            End Set
        End Property
        
        '''<remarks/>
        <System.Xml.Serialization.XmlElementAttribute(Form:=System.Xml.Schema.XmlSchemaForm.Unqualified, Order:=1)>  _
        Public Property value() As String
            Get
                Return Me.valueField
            End Get
            Set
                Me.valueField = value
                Me.RaisePropertyChanged("value")
            End Set
        End Property
        
        Public Event PropertyChanged As System.ComponentModel.PropertyChangedEventHandler Implements System.ComponentModel.INotifyPropertyChanged.PropertyChanged
        
        Protected Sub RaisePropertyChanged(ByVal propertyName As String)
            Dim propertyChanged As System.ComponentModel.PropertyChangedEventHandler = Me.PropertyChangedEvent
            If (Not (propertyChanged) Is Nothing) Then
                propertyChanged(Me, New System.ComponentModel.PropertyChangedEventArgs(propertyName))
            End If
        End Sub
    End Class
    
    '''<remarks/>
    <System.CodeDom.Compiler.GeneratedCodeAttribute("System.Xml", "4.0.30319.17929"),  _
     System.SerializableAttribute(),  _
     System.Diagnostics.DebuggerStepThroughAttribute(),  _
     System.ComponentModel.DesignerCategoryAttribute("code"),  _
     System.Xml.Serialization.XmlTypeAttribute([Namespace]:="http://www.fedora.info/definitions/1/0/types/")>  _
    Partial Public Class MIMETypedStream
        Inherits Object
        Implements System.ComponentModel.INotifyPropertyChanged
        
        Private mIMETypeField As String
        
        Private streamField() As Byte
        
        Private headerField() As [Property]
        
        '''<remarks/>
        <System.Xml.Serialization.XmlElementAttribute(Form:=System.Xml.Schema.XmlSchemaForm.Unqualified, IsNullable:=true, Order:=0)>  _
        Public Property MIMEType() As String
            Get
                Return Me.mIMETypeField
            End Get
            Set
                Me.mIMETypeField = value
                Me.RaisePropertyChanged("MIMEType")
            End Set
        End Property
        
        '''<remarks/>
        <System.Xml.Serialization.XmlElementAttribute(Form:=System.Xml.Schema.XmlSchemaForm.Unqualified, DataType:="base64Binary", IsNullable:=true, Order:=1)>  _
        Public Property stream() As Byte()
            Get
                Return Me.streamField
            End Get
            Set
                Me.streamField = value
                Me.RaisePropertyChanged("stream")
            End Set
        End Property
        
        '''<remarks/>
        <System.Xml.Serialization.XmlArrayAttribute(Form:=System.Xml.Schema.XmlSchemaForm.Unqualified, IsNullable:=true, Order:=2),  _
         System.Xml.Serialization.XmlArrayItemAttribute("property", Form:=System.Xml.Schema.XmlSchemaForm.Unqualified, IsNullable:=false)>  _
        Public Property header() As [Property]()
            Get
                Return Me.headerField
            End Get
            Set
                Me.headerField = value
                Me.RaisePropertyChanged("header")
            End Set
        End Property
        
        Public Event PropertyChanged As System.ComponentModel.PropertyChangedEventHandler Implements System.ComponentModel.INotifyPropertyChanged.PropertyChanged
        
        Protected Sub RaisePropertyChanged(ByVal propertyName As String)
            Dim propertyChanged As System.ComponentModel.PropertyChangedEventHandler = Me.PropertyChangedEvent
            If (Not (propertyChanged) Is Nothing) Then
                propertyChanged(Me, New System.ComponentModel.PropertyChangedEventArgs(propertyName))
            End If
        End Sub
    End Class
    
    '''<remarks/>
    <System.CodeDom.Compiler.GeneratedCodeAttribute("System.Xml", "4.0.30319.17929"),  _
     System.SerializableAttribute(),  _
     System.Diagnostics.DebuggerStepThroughAttribute(),  _
     System.ComponentModel.DesignerCategoryAttribute("code"),  _
     System.Xml.Serialization.XmlTypeAttribute([Namespace]:="http://www.fedora.info/definitions/1/0/types/")>  _
    Partial Public Class DatastreamDef
        Inherits Object
        Implements System.ComponentModel.INotifyPropertyChanged
        
        Private idField As String
        
        Private labelField As String
        
        Private mIMETypeField As String
        
        '''<remarks/>
        <System.Xml.Serialization.XmlElementAttribute(Form:=System.Xml.Schema.XmlSchemaForm.Unqualified, IsNullable:=true, Order:=0)>  _
        Public Property ID() As String
            Get
                Return Me.idField
            End Get
            Set
                Me.idField = value
                Me.RaisePropertyChanged("ID")
            End Set
        End Property
        
        '''<remarks/>
        <System.Xml.Serialization.XmlElementAttribute(Form:=System.Xml.Schema.XmlSchemaForm.Unqualified, IsNullable:=true, Order:=1)>  _
        Public Property label() As String
            Get
                Return Me.labelField
            End Get
            Set
                Me.labelField = value
                Me.RaisePropertyChanged("label")
            End Set
        End Property
        
        '''<remarks/>
        <System.Xml.Serialization.XmlElementAttribute(Form:=System.Xml.Schema.XmlSchemaForm.Unqualified, IsNullable:=true, Order:=2)>  _
        Public Property MIMEType() As String
            Get
                Return Me.mIMETypeField
            End Get
            Set
                Me.mIMETypeField = value
                Me.RaisePropertyChanged("MIMEType")
            End Set
        End Property
        
        Public Event PropertyChanged As System.ComponentModel.PropertyChangedEventHandler Implements System.ComponentModel.INotifyPropertyChanged.PropertyChanged
        
        Protected Sub RaisePropertyChanged(ByVal propertyName As String)
            Dim propertyChanged As System.ComponentModel.PropertyChangedEventHandler = Me.PropertyChangedEvent
            If (Not (propertyChanged) Is Nothing) Then
                propertyChanged(Me, New System.ComponentModel.PropertyChangedEventArgs(propertyName))
            End If
        End Sub
    End Class
    
    '''<remarks/>
    <System.CodeDom.Compiler.GeneratedCodeAttribute("System.Xml", "4.0.30319.17929"),  _
     System.SerializableAttribute(),  _
     System.Diagnostics.DebuggerStepThroughAttribute(),  _
     System.ComponentModel.DesignerCategoryAttribute("code"),  _
     System.Xml.Serialization.XmlTypeAttribute([Namespace]:="http://www.fedora.info/definitions/1/0/types/")>  _
    Partial Public Class MethodParmDef
        Inherits Object
        Implements System.ComponentModel.INotifyPropertyChanged
        
        Private parmNameField As String
        
        Private parmTypeField As String
        
        Private parmDefaultValueField As String
        
        Private parmDomainValuesField() As String
        
        Private parmRequiredField As Boolean
        
        Private parmLabelField As String
        
        Private parmPassByField As String
        
        Private pASS_BY_REFField As System.Nullable(Of passByRef)
        
        Private pASS_BY_VALUEField As System.Nullable(Of passByValue)
        
        Private dATASTREAM_INPUTField As System.Nullable(Of datastreamInputType)
        
        Private uSER_INPUTField As System.Nullable(Of userInputType)
        
        Private dEFAULT_INPUTField As System.Nullable(Of defaultInputType)
        
        '''<remarks/>
        <System.Xml.Serialization.XmlElementAttribute(Form:=System.Xml.Schema.XmlSchemaForm.Unqualified, IsNullable:=true, Order:=0)>  _
        Public Property parmName() As String
            Get
                Return Me.parmNameField
            End Get
            Set
                Me.parmNameField = value
                Me.RaisePropertyChanged("parmName")
            End Set
        End Property
        
        '''<remarks/>
        <System.Xml.Serialization.XmlElementAttribute(Form:=System.Xml.Schema.XmlSchemaForm.Unqualified, IsNullable:=true, Order:=1)>  _
        Public Property parmType() As String
            Get
                Return Me.parmTypeField
            End Get
            Set
                Me.parmTypeField = value
                Me.RaisePropertyChanged("parmType")
            End Set
        End Property
        
        '''<remarks/>
        <System.Xml.Serialization.XmlElementAttribute(Form:=System.Xml.Schema.XmlSchemaForm.Unqualified, IsNullable:=true, Order:=2)>  _
        Public Property parmDefaultValue() As String
            Get
                Return Me.parmDefaultValueField
            End Get
            Set
                Me.parmDefaultValueField = value
                Me.RaisePropertyChanged("parmDefaultValue")
            End Set
        End Property
        
        '''<remarks/>
        <System.Xml.Serialization.XmlArrayAttribute(Form:=System.Xml.Schema.XmlSchemaForm.Unqualified, IsNullable:=true, Order:=3),  _
         System.Xml.Serialization.XmlArrayItemAttribute("item", Form:=System.Xml.Schema.XmlSchemaForm.Unqualified, IsNullable:=false)>  _
        Public Property parmDomainValues() As String()
            Get
                Return Me.parmDomainValuesField
            End Get
            Set
                Me.parmDomainValuesField = value
                Me.RaisePropertyChanged("parmDomainValues")
            End Set
        End Property
        
        '''<remarks/>
        <System.Xml.Serialization.XmlElementAttribute(Form:=System.Xml.Schema.XmlSchemaForm.Unqualified, Order:=4)>  _
        Public Property parmRequired() As Boolean
            Get
                Return Me.parmRequiredField
            End Get
            Set
                Me.parmRequiredField = value
                Me.RaisePropertyChanged("parmRequired")
            End Set
        End Property
        
        '''<remarks/>
        <System.Xml.Serialization.XmlElementAttribute(Form:=System.Xml.Schema.XmlSchemaForm.Unqualified, IsNullable:=true, Order:=5)>  _
        Public Property parmLabel() As String
            Get
                Return Me.parmLabelField
            End Get
            Set
                Me.parmLabelField = value
                Me.RaisePropertyChanged("parmLabel")
            End Set
        End Property
        
        '''<remarks/>
        <System.Xml.Serialization.XmlElementAttribute(Form:=System.Xml.Schema.XmlSchemaForm.Unqualified, IsNullable:=true, Order:=6)>  _
        Public Property parmPassBy() As String
            Get
                Return Me.parmPassByField
            End Get
            Set
                Me.parmPassByField = value
                Me.RaisePropertyChanged("parmPassBy")
            End Set
        End Property
        
        '''<remarks/>
        <System.Xml.Serialization.XmlElementAttribute(Form:=System.Xml.Schema.XmlSchemaForm.Unqualified, IsNullable:=true, Order:=7)>  _
        Public Property PASS_BY_REF() As System.Nullable(Of passByRef)
            Get
                Return Me.pASS_BY_REFField
            End Get
            Set
                Me.pASS_BY_REFField = value
                Me.RaisePropertyChanged("PASS_BY_REF")
            End Set
        End Property
        
        '''<remarks/>
        <System.Xml.Serialization.XmlElementAttribute(Form:=System.Xml.Schema.XmlSchemaForm.Unqualified, IsNullable:=true, Order:=8)>  _
        Public Property PASS_BY_VALUE() As System.Nullable(Of passByValue)
            Get
                Return Me.pASS_BY_VALUEField
            End Get
            Set
                Me.pASS_BY_VALUEField = value
                Me.RaisePropertyChanged("PASS_BY_VALUE")
            End Set
        End Property
        
        '''<remarks/>
        <System.Xml.Serialization.XmlElementAttribute(Form:=System.Xml.Schema.XmlSchemaForm.Unqualified, IsNullable:=true, Order:=9)>  _
        Public Property DATASTREAM_INPUT() As System.Nullable(Of datastreamInputType)
            Get
                Return Me.dATASTREAM_INPUTField
            End Get
            Set
                Me.dATASTREAM_INPUTField = value
                Me.RaisePropertyChanged("DATASTREAM_INPUT")
            End Set
        End Property
        
        '''<remarks/>
        <System.Xml.Serialization.XmlElementAttribute(Form:=System.Xml.Schema.XmlSchemaForm.Unqualified, IsNullable:=true, Order:=10)>  _
        Public Property USER_INPUT() As System.Nullable(Of userInputType)
            Get
                Return Me.uSER_INPUTField
            End Get
            Set
                Me.uSER_INPUTField = value
                Me.RaisePropertyChanged("USER_INPUT")
            End Set
        End Property
        
        '''<remarks/>
        <System.Xml.Serialization.XmlElementAttribute(Form:=System.Xml.Schema.XmlSchemaForm.Unqualified, IsNullable:=true, Order:=11)>  _
        Public Property DEFAULT_INPUT() As System.Nullable(Of defaultInputType)
            Get
                Return Me.dEFAULT_INPUTField
            End Get
            Set
                Me.dEFAULT_INPUTField = value
                Me.RaisePropertyChanged("DEFAULT_INPUT")
            End Set
        End Property
        
        Public Event PropertyChanged As System.ComponentModel.PropertyChangedEventHandler Implements System.ComponentModel.INotifyPropertyChanged.PropertyChanged
        
        Protected Sub RaisePropertyChanged(ByVal propertyName As String)
            Dim propertyChanged As System.ComponentModel.PropertyChangedEventHandler = Me.PropertyChangedEvent
            If (Not (propertyChanged) Is Nothing) Then
                propertyChanged(Me, New System.ComponentModel.PropertyChangedEventArgs(propertyName))
            End If
        End Sub
    End Class
    
    '''<remarks/>
    <System.CodeDom.Compiler.GeneratedCodeAttribute("System.Xml", "4.0.30319.17929"),  _
     System.SerializableAttribute(),  _
     System.Xml.Serialization.XmlTypeAttribute([Namespace]:="http://www.fedora.info/definitions/1/0/types/")>  _
    Public Enum passByRef
        
        '''<remarks/>
        URL_REF
    End Enum
    
    '''<remarks/>
    <System.CodeDom.Compiler.GeneratedCodeAttribute("System.Xml", "4.0.30319.17929"),  _
     System.SerializableAttribute(),  _
     System.Xml.Serialization.XmlTypeAttribute([Namespace]:="http://www.fedora.info/definitions/1/0/types/")>  _
    Public Enum passByValue
        
        '''<remarks/>
        VALUE
    End Enum
    
    '''<remarks/>
    <System.CodeDom.Compiler.GeneratedCodeAttribute("System.Xml", "4.0.30319.17929"),  _
     System.SerializableAttribute(),  _
     System.Xml.Serialization.XmlTypeAttribute([Namespace]:="http://www.fedora.info/definitions/1/0/types/")>  _
    Public Enum datastreamInputType
        
        '''<remarks/>
        <System.Xml.Serialization.XmlEnumAttribute("fedora:datastreamInputType")>  _
        fedoradatastreamInputType
    End Enum
    
    '''<remarks/>
    <System.CodeDom.Compiler.GeneratedCodeAttribute("System.Xml", "4.0.30319.17929"),  _
     System.SerializableAttribute(),  _
     System.Xml.Serialization.XmlTypeAttribute([Namespace]:="http://www.fedora.info/definitions/1/0/types/")>  _
    Public Enum userInputType
        
        '''<remarks/>
        <System.Xml.Serialization.XmlEnumAttribute("fedora:userInputType")>  _
        fedorauserInputType
    End Enum
    
    '''<remarks/>
    <System.CodeDom.Compiler.GeneratedCodeAttribute("System.Xml", "4.0.30319.17929"),  _
     System.SerializableAttribute(),  _
     System.Xml.Serialization.XmlTypeAttribute([Namespace]:="http://www.fedora.info/definitions/1/0/types/")>  _
    Public Enum defaultInputType
        
        '''<remarks/>
        <System.Xml.Serialization.XmlEnumAttribute("fedora:defaultInputType")>  _
        fedoradefaultInputType
    End Enum
    
    '''<remarks/>
    <System.CodeDom.Compiler.GeneratedCodeAttribute("System.Xml", "4.0.30319.17929"),  _
     System.SerializableAttribute(),  _
     System.Diagnostics.DebuggerStepThroughAttribute(),  _
     System.ComponentModel.DesignerCategoryAttribute("code"),  _
     System.Xml.Serialization.XmlTypeAttribute([Namespace]:="http://www.fedora.info/definitions/1/0/types/")>  _
    Partial Public Class ObjectMethodsDef
        Inherits Object
        Implements System.ComponentModel.INotifyPropertyChanged
        
        Private pIDField As String
        
        Private serviceDefinitionPIDField As String
        
        Private methodNameField As String
        
        Private methodParmDefsField() As MethodParmDef
        
        Private asOfDateField As String
        
        '''<remarks/>
        <System.Xml.Serialization.XmlElementAttribute(Form:=System.Xml.Schema.XmlSchemaForm.Unqualified, Order:=0)>  _
        Public Property PID() As String
            Get
                Return Me.pIDField
            End Get
            Set
                Me.pIDField = value
                Me.RaisePropertyChanged("PID")
            End Set
        End Property
        
        '''<remarks/>
        <System.Xml.Serialization.XmlElementAttribute(Form:=System.Xml.Schema.XmlSchemaForm.Unqualified, Order:=1)>  _
        Public Property serviceDefinitionPID() As String
            Get
                Return Me.serviceDefinitionPIDField
            End Get
            Set
                Me.serviceDefinitionPIDField = value
                Me.RaisePropertyChanged("serviceDefinitionPID")
            End Set
        End Property
        
        '''<remarks/>
        <System.Xml.Serialization.XmlElementAttribute(Form:=System.Xml.Schema.XmlSchemaForm.Unqualified, Order:=2)>  _
        Public Property methodName() As String
            Get
                Return Me.methodNameField
            End Get
            Set
                Me.methodNameField = value
                Me.RaisePropertyChanged("methodName")
            End Set
        End Property
        
        '''<remarks/>
        <System.Xml.Serialization.XmlArrayAttribute(Form:=System.Xml.Schema.XmlSchemaForm.Unqualified, Order:=3),  _
         System.Xml.Serialization.XmlArrayItemAttribute("methodParmDef", Form:=System.Xml.Schema.XmlSchemaForm.Unqualified, IsNullable:=false)>  _
        Public Property methodParmDefs() As MethodParmDef()
            Get
                Return Me.methodParmDefsField
            End Get
            Set
                Me.methodParmDefsField = value
                Me.RaisePropertyChanged("methodParmDefs")
            End Set
        End Property
        
        '''<remarks/>
        <System.Xml.Serialization.XmlElementAttribute(Form:=System.Xml.Schema.XmlSchemaForm.Unqualified, IsNullable:=true, Order:=4)>  _
        Public Property asOfDate() As String
            Get
                Return Me.asOfDateField
            End Get
            Set
                Me.asOfDateField = value
                Me.RaisePropertyChanged("asOfDate")
            End Set
        End Property
        
        Public Event PropertyChanged As System.ComponentModel.PropertyChangedEventHandler Implements System.ComponentModel.INotifyPropertyChanged.PropertyChanged
        
        Protected Sub RaisePropertyChanged(ByVal propertyName As String)
            Dim propertyChanged As System.ComponentModel.PropertyChangedEventHandler = Me.PropertyChangedEvent
            If (Not (propertyChanged) Is Nothing) Then
                propertyChanged(Me, New System.ComponentModel.PropertyChangedEventArgs(propertyName))
            End If
        End Sub
    End Class
    
    '''<remarks/>
    <System.CodeDom.Compiler.GeneratedCodeAttribute("System.Xml", "4.0.30319.17929"),  _
     System.SerializableAttribute(),  _
     System.Diagnostics.DebuggerStepThroughAttribute(),  _
     System.ComponentModel.DesignerCategoryAttribute("code"),  _
     System.Xml.Serialization.XmlTypeAttribute([Namespace]:="http://www.fedora.info/definitions/1/0/types/")>  _
    Partial Public Class ObjectProfile
        Inherits Object
        Implements System.ComponentModel.INotifyPropertyChanged
        
        Private pidField As String
        
        Private objLabelField As String
        
        Private objModelsField() As String
        
        Private objCreateDateField As String
        
        Private objLastModDateField As String
        
        Private objDissIndexViewURLField As String
        
        Private objItemIndexViewURLField As String
        
        '''<remarks/>
        <System.Xml.Serialization.XmlElementAttribute(Form:=System.Xml.Schema.XmlSchemaForm.Unqualified, IsNullable:=true, Order:=0)>  _
        Public Property pid() As String
            Get
                Return Me.pidField
            End Get
            Set
                Me.pidField = value
                Me.RaisePropertyChanged("pid")
            End Set
        End Property
        
        '''<remarks/>
        <System.Xml.Serialization.XmlElementAttribute(Form:=System.Xml.Schema.XmlSchemaForm.Unqualified, IsNullable:=true, Order:=1)>  _
        Public Property objLabel() As String
            Get
                Return Me.objLabelField
            End Get
            Set
                Me.objLabelField = value
                Me.RaisePropertyChanged("objLabel")
            End Set
        End Property
        
        '''<remarks/>
        <System.Xml.Serialization.XmlArrayAttribute(Form:=System.Xml.Schema.XmlSchemaForm.Unqualified, IsNullable:=true, Order:=2),  _
         System.Xml.Serialization.XmlArrayItemAttribute("model", Form:=System.Xml.Schema.XmlSchemaForm.Unqualified, IsNullable:=false)>  _
        Public Property objModels() As String()
            Get
                Return Me.objModelsField
            End Get
            Set
                Me.objModelsField = value
                Me.RaisePropertyChanged("objModels")
            End Set
        End Property
        
        '''<remarks/>
        <System.Xml.Serialization.XmlElementAttribute(Form:=System.Xml.Schema.XmlSchemaForm.Unqualified, IsNullable:=true, Order:=3)>  _
        Public Property objCreateDate() As String
            Get
                Return Me.objCreateDateField
            End Get
            Set
                Me.objCreateDateField = value
                Me.RaisePropertyChanged("objCreateDate")
            End Set
        End Property
        
        '''<remarks/>
        <System.Xml.Serialization.XmlElementAttribute(Form:=System.Xml.Schema.XmlSchemaForm.Unqualified, IsNullable:=true, Order:=4)>  _
        Public Property objLastModDate() As String
            Get
                Return Me.objLastModDateField
            End Get
            Set
                Me.objLastModDateField = value
                Me.RaisePropertyChanged("objLastModDate")
            End Set
        End Property
        
        '''<remarks/>
        <System.Xml.Serialization.XmlElementAttribute(Form:=System.Xml.Schema.XmlSchemaForm.Unqualified, IsNullable:=true, Order:=5)>  _
        Public Property objDissIndexViewURL() As String
            Get
                Return Me.objDissIndexViewURLField
            End Get
            Set
                Me.objDissIndexViewURLField = value
                Me.RaisePropertyChanged("objDissIndexViewURL")
            End Set
        End Property
        
        '''<remarks/>
        <System.Xml.Serialization.XmlElementAttribute(Form:=System.Xml.Schema.XmlSchemaForm.Unqualified, IsNullable:=true, Order:=6)>  _
        Public Property objItemIndexViewURL() As String
            Get
                Return Me.objItemIndexViewURLField
            End Get
            Set
                Me.objItemIndexViewURLField = value
                Me.RaisePropertyChanged("objItemIndexViewURL")
            End Set
        End Property
        
        Public Event PropertyChanged As System.ComponentModel.PropertyChangedEventHandler Implements System.ComponentModel.INotifyPropertyChanged.PropertyChanged
        
        Protected Sub RaisePropertyChanged(ByVal propertyName As String)
            Dim propertyChanged As System.ComponentModel.PropertyChangedEventHandler = Me.PropertyChangedEvent
            If (Not (propertyChanged) Is Nothing) Then
                propertyChanged(Me, New System.ComponentModel.PropertyChangedEventArgs(propertyName))
            End If
        End Sub
    End Class
    
    <System.Diagnostics.DebuggerStepThroughAttribute(),  _
     System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0"),  _
     System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced),  _
     System.ServiceModel.MessageContractAttribute(WrapperName:="describeRepository", WrapperNamespace:="http://www.fedora.info/definitions/1/0/types/", IsWrapped:=true)>  _
    Partial Public Class describeRepositoryRequest
        
        Public Sub New()
            MyBase.New
        End Sub
    End Class
    
    <System.Diagnostics.DebuggerStepThroughAttribute(),  _
     System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0"),  _
     System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced),  _
     System.ServiceModel.MessageContractAttribute(WrapperName:="describeRepositoryResponse", WrapperNamespace:="http://www.fedora.info/definitions/1/0/types/", IsWrapped:=true)>  _
    Partial Public Class describeRepositoryResponse
        
        <System.ServiceModel.MessageBodyMemberAttribute([Namespace]:="http://www.fedora.info/definitions/1/0/types/", Order:=0),  _
         System.Xml.Serialization.XmlElementAttribute(Form:=System.Xml.Schema.XmlSchemaForm.Unqualified)>  _
        Public repositoryInfo As ApiA.RepositoryInfo
        
        Public Sub New()
            MyBase.New
        End Sub
        
        Public Sub New(ByVal repositoryInfo As ApiA.RepositoryInfo)
            MyBase.New
            Me.repositoryInfo = repositoryInfo
        End Sub
    End Class
    
    <System.Diagnostics.DebuggerStepThroughAttribute(),  _
     System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0"),  _
     System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced),  _
     System.ServiceModel.MessageContractAttribute(WrapperName:="getObjectProfile", WrapperNamespace:="http://www.fedora.info/definitions/1/0/types/", IsWrapped:=true)>  _
    Partial Public Class getObjectProfileRequest
        
        <System.ServiceModel.MessageBodyMemberAttribute([Namespace]:="http://www.fedora.info/definitions/1/0/types/", Order:=0),  _
         System.Xml.Serialization.XmlElementAttribute(Form:=System.Xml.Schema.XmlSchemaForm.Unqualified)>  _
        Public pid As String
        
        <System.ServiceModel.MessageBodyMemberAttribute([Namespace]:="http://www.fedora.info/definitions/1/0/types/", Order:=1),  _
         System.Xml.Serialization.XmlElementAttribute(Form:=System.Xml.Schema.XmlSchemaForm.Unqualified, IsNullable:=true)>  _
        Public asOfDateTime As String
        
        Public Sub New()
            MyBase.New
        End Sub
        
        Public Sub New(ByVal pid As String, ByVal asOfDateTime As String)
            MyBase.New
            Me.pid = pid
            Me.asOfDateTime = asOfDateTime
        End Sub
    End Class
    
    <System.Diagnostics.DebuggerStepThroughAttribute(),  _
     System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0"),  _
     System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced),  _
     System.ServiceModel.MessageContractAttribute(WrapperName:="getObjectProfileResponse", WrapperNamespace:="http://www.fedora.info/definitions/1/0/types/", IsWrapped:=true)>  _
    Partial Public Class getObjectProfileResponse
        
        <System.ServiceModel.MessageBodyMemberAttribute([Namespace]:="http://www.fedora.info/definitions/1/0/types/", Order:=0),  _
         System.Xml.Serialization.XmlElementAttribute(Form:=System.Xml.Schema.XmlSchemaForm.Unqualified)>  _
        Public objectProfile As ApiA.ObjectProfile
        
        Public Sub New()
            MyBase.New
        End Sub
        
        Public Sub New(ByVal objectProfile As ApiA.ObjectProfile)
            MyBase.New
            Me.objectProfile = objectProfile
        End Sub
    End Class
    
    <System.Diagnostics.DebuggerStepThroughAttribute(),  _
     System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0"),  _
     System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced),  _
     System.ServiceModel.MessageContractAttribute(WrapperName:="listMethods", WrapperNamespace:="http://www.fedora.info/definitions/1/0/types/", IsWrapped:=true)>  _
    Partial Public Class listMethodsRequest
        
        <System.ServiceModel.MessageBodyMemberAttribute([Namespace]:="http://www.fedora.info/definitions/1/0/types/", Order:=0),  _
         System.Xml.Serialization.XmlElementAttribute(Form:=System.Xml.Schema.XmlSchemaForm.Unqualified)>  _
        Public pid As String
        
        <System.ServiceModel.MessageBodyMemberAttribute([Namespace]:="http://www.fedora.info/definitions/1/0/types/", Order:=1),  _
         System.Xml.Serialization.XmlElementAttribute(Form:=System.Xml.Schema.XmlSchemaForm.Unqualified, IsNullable:=true)>  _
        Public asOfDateTime As String
        
        Public Sub New()
            MyBase.New
        End Sub
        
        Public Sub New(ByVal pid As String, ByVal asOfDateTime As String)
            MyBase.New
            Me.pid = pid
            Me.asOfDateTime = asOfDateTime
        End Sub
    End Class
    
    <System.Diagnostics.DebuggerStepThroughAttribute(),  _
     System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0"),  _
     System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced),  _
     System.ServiceModel.MessageContractAttribute(WrapperName:="listMethodsResponse", WrapperNamespace:="http://www.fedora.info/definitions/1/0/types/", IsWrapped:=true)>  _
    Partial Public Class listMethodsResponse
        
        <System.ServiceModel.MessageBodyMemberAttribute([Namespace]:="http://www.fedora.info/definitions/1/0/types/", Order:=0),  _
         System.Xml.Serialization.XmlElementAttribute("objectMethod", Form:=System.Xml.Schema.XmlSchemaForm.Unqualified)>  _
        Public objectMethod() As ApiA.ObjectMethodsDef
        
        Public Sub New()
            MyBase.New
        End Sub
        
        Public Sub New(ByVal objectMethod() As ApiA.ObjectMethodsDef)
            MyBase.New
            Me.objectMethod = objectMethod
        End Sub
    End Class
    
    <System.Diagnostics.DebuggerStepThroughAttribute(),  _
     System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0"),  _
     System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced),  _
     System.ServiceModel.MessageContractAttribute(WrapperName:="listDatastreams", WrapperNamespace:="http://www.fedora.info/definitions/1/0/types/", IsWrapped:=true)>  _
    Partial Public Class listDatastreamsRequest
        
        <System.ServiceModel.MessageBodyMemberAttribute([Namespace]:="http://www.fedora.info/definitions/1/0/types/", Order:=0),  _
         System.Xml.Serialization.XmlElementAttribute(Form:=System.Xml.Schema.XmlSchemaForm.Unqualified)>  _
        Public pid As String
        
        <System.ServiceModel.MessageBodyMemberAttribute([Namespace]:="http://www.fedora.info/definitions/1/0/types/", Order:=1),  _
         System.Xml.Serialization.XmlElementAttribute(Form:=System.Xml.Schema.XmlSchemaForm.Unqualified, IsNullable:=true)>  _
        Public asOfDateTime As String
        
        Public Sub New()
            MyBase.New
        End Sub
        
        Public Sub New(ByVal pid As String, ByVal asOfDateTime As String)
            MyBase.New
            Me.pid = pid
            Me.asOfDateTime = asOfDateTime
        End Sub
    End Class
    
    <System.Diagnostics.DebuggerStepThroughAttribute(),  _
     System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0"),  _
     System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced),  _
     System.ServiceModel.MessageContractAttribute(WrapperName:="listDatastreamsResponse", WrapperNamespace:="http://www.fedora.info/definitions/1/0/types/", IsWrapped:=true)>  _
    Partial Public Class listDatastreamsResponse
        
        <System.ServiceModel.MessageBodyMemberAttribute([Namespace]:="http://www.fedora.info/definitions/1/0/types/", Order:=0),  _
         System.Xml.Serialization.XmlElementAttribute("datastreamDef", Form:=System.Xml.Schema.XmlSchemaForm.Unqualified)>  _
        Public datastreamDef() As ApiA.DatastreamDef
        
        Public Sub New()
            MyBase.New
        End Sub
        
        Public Sub New(ByVal datastreamDef() As ApiA.DatastreamDef)
            MyBase.New
            Me.datastreamDef = datastreamDef
        End Sub
    End Class
    
    <System.Diagnostics.DebuggerStepThroughAttribute(),  _
     System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0"),  _
     System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced),  _
     System.ServiceModel.MessageContractAttribute(WrapperName:="getDatastreamDissemination", WrapperNamespace:="http://www.fedora.info/definitions/1/0/types/", IsWrapped:=true)>  _
    Partial Public Class getDatastreamDisseminationRequest
        
        <System.ServiceModel.MessageBodyMemberAttribute([Namespace]:="http://www.fedora.info/definitions/1/0/types/", Order:=0),  _
         System.Xml.Serialization.XmlElementAttribute(Form:=System.Xml.Schema.XmlSchemaForm.Unqualified)>  _
        Public pid As String
        
        <System.ServiceModel.MessageBodyMemberAttribute([Namespace]:="http://www.fedora.info/definitions/1/0/types/", Order:=1),  _
         System.Xml.Serialization.XmlElementAttribute(Form:=System.Xml.Schema.XmlSchemaForm.Unqualified)>  _
        Public dsID As String
        
        <System.ServiceModel.MessageBodyMemberAttribute([Namespace]:="http://www.fedora.info/definitions/1/0/types/", Order:=2),  _
         System.Xml.Serialization.XmlElementAttribute(Form:=System.Xml.Schema.XmlSchemaForm.Unqualified, IsNullable:=true)>  _
        Public asOfDateTime As String
        
        Public Sub New()
            MyBase.New
        End Sub
        
        Public Sub New(ByVal pid As String, ByVal dsID As String, ByVal asOfDateTime As String)
            MyBase.New
            Me.pid = pid
            Me.dsID = dsID
            Me.asOfDateTime = asOfDateTime
        End Sub
    End Class
    
    <System.Diagnostics.DebuggerStepThroughAttribute(),  _
     System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0"),  _
     System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced),  _
     System.ServiceModel.MessageContractAttribute(WrapperName:="getDatastreamDisseminationResponse", WrapperNamespace:="http://www.fedora.info/definitions/1/0/types/", IsWrapped:=true)>  _
    Partial Public Class getDatastreamDisseminationResponse
        
        <System.ServiceModel.MessageBodyMemberAttribute([Namespace]:="http://www.fedora.info/definitions/1/0/types/", Order:=0),  _
         System.Xml.Serialization.XmlElementAttribute(Form:=System.Xml.Schema.XmlSchemaForm.Unqualified)>  _
        Public dissemination As ApiA.MIMETypedStream
        
        Public Sub New()
            MyBase.New
        End Sub
        
        Public Sub New(ByVal dissemination As ApiA.MIMETypedStream)
            MyBase.New
            Me.dissemination = dissemination
        End Sub
    End Class
    
    <System.Diagnostics.DebuggerStepThroughAttribute(),  _
     System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0"),  _
     System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced),  _
     System.ServiceModel.MessageContractAttribute(WrapperName:="getDissemination", WrapperNamespace:="http://www.fedora.info/definitions/1/0/types/", IsWrapped:=true)>  _
    Partial Public Class getDisseminationRequest
        
        <System.ServiceModel.MessageBodyMemberAttribute([Namespace]:="http://www.fedora.info/definitions/1/0/types/", Order:=0),  _
         System.Xml.Serialization.XmlElementAttribute(Form:=System.Xml.Schema.XmlSchemaForm.Unqualified)>  _
        Public pid As String
        
        <System.ServiceModel.MessageBodyMemberAttribute([Namespace]:="http://www.fedora.info/definitions/1/0/types/", Order:=1),  _
         System.Xml.Serialization.XmlElementAttribute(Form:=System.Xml.Schema.XmlSchemaForm.Unqualified)>  _
        Public serviceDefinitionPid As String
        
        <System.ServiceModel.MessageBodyMemberAttribute([Namespace]:="http://www.fedora.info/definitions/1/0/types/", Order:=2),  _
         System.Xml.Serialization.XmlElementAttribute(Form:=System.Xml.Schema.XmlSchemaForm.Unqualified)>  _
        Public methodName As String
        
        <System.ServiceModel.MessageBodyMemberAttribute([Namespace]:="http://www.fedora.info/definitions/1/0/types/", Order:=3),  _
         System.Xml.Serialization.XmlArrayAttribute(Form:=System.Xml.Schema.XmlSchemaForm.Unqualified),  _
         System.Xml.Serialization.XmlArrayItemAttribute("parameter", Form:=System.Xml.Schema.XmlSchemaForm.Unqualified, IsNullable:=false)>  _
        Public parameters() As ApiA.[Property]
        
        <System.ServiceModel.MessageBodyMemberAttribute([Namespace]:="http://www.fedora.info/definitions/1/0/types/", Order:=4),  _
         System.Xml.Serialization.XmlElementAttribute(Form:=System.Xml.Schema.XmlSchemaForm.Unqualified, IsNullable:=true)>  _
        Public asOfDateTime As String
        
        Public Sub New()
            MyBase.New
        End Sub
        
        Public Sub New(ByVal pid As String, ByVal serviceDefinitionPid As String, ByVal methodName As String, ByVal parameters() As ApiA.[Property], ByVal asOfDateTime As String)
            MyBase.New
            Me.pid = pid
            Me.serviceDefinitionPid = serviceDefinitionPid
            Me.methodName = methodName
            Me.parameters = parameters
            Me.asOfDateTime = asOfDateTime
        End Sub
    End Class
    
    <System.Diagnostics.DebuggerStepThroughAttribute(),  _
     System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0"),  _
     System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced),  _
     System.ServiceModel.MessageContractAttribute(WrapperName:="getDisseminationResponse", WrapperNamespace:="http://www.fedora.info/definitions/1/0/types/", IsWrapped:=true)>  _
    Partial Public Class getDisseminationResponse
        
        <System.ServiceModel.MessageBodyMemberAttribute([Namespace]:="http://www.fedora.info/definitions/1/0/types/", Order:=0),  _
         System.Xml.Serialization.XmlElementAttribute(Form:=System.Xml.Schema.XmlSchemaForm.Unqualified)>  _
        Public dissemination As ApiA.MIMETypedStream
        
        Public Sub New()
            MyBase.New
        End Sub
        
        Public Sub New(ByVal dissemination As ApiA.MIMETypedStream)
            MyBase.New
            Me.dissemination = dissemination
        End Sub
    End Class
    
    <System.Diagnostics.DebuggerStepThroughAttribute(),  _
     System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0"),  _
     System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced),  _
     System.ServiceModel.MessageContractAttribute(WrapperName:="findObjects", WrapperNamespace:="http://www.fedora.info/definitions/1/0/types/", IsWrapped:=true)>  _
    Partial Public Class findObjectsRequest
        
        <System.ServiceModel.MessageBodyMemberAttribute([Namespace]:="http://www.fedora.info/definitions/1/0/types/", Order:=0),  _
         System.Xml.Serialization.XmlArrayAttribute(Form:=System.Xml.Schema.XmlSchemaForm.Unqualified),  _
         System.Xml.Serialization.XmlArrayItemAttribute("item", Form:=System.Xml.Schema.XmlSchemaForm.Unqualified, IsNullable:=false)>  _
        Public resultFields() As String
        
        <System.ServiceModel.MessageBodyMemberAttribute([Namespace]:="http://www.fedora.info/definitions/1/0/types/", Order:=1),  _
         System.Xml.Serialization.XmlElementAttribute(Form:=System.Xml.Schema.XmlSchemaForm.Unqualified, DataType:="nonNegativeInteger")>  _
        Public maxResults As String
        
        <System.ServiceModel.MessageBodyMemberAttribute([Namespace]:="http://www.fedora.info/definitions/1/0/types/", Order:=2),  _
         System.Xml.Serialization.XmlElementAttribute(Form:=System.Xml.Schema.XmlSchemaForm.Unqualified)>  _
        Public query As ApiA.FieldSearchQuery
        
        Public Sub New()
            MyBase.New
        End Sub
        
        Public Sub New(ByVal resultFields() As String, ByVal maxResults As String, ByVal query As ApiA.FieldSearchQuery)
            MyBase.New
            Me.resultFields = resultFields
            Me.maxResults = maxResults
            Me.query = query
        End Sub
    End Class
    
    <System.Diagnostics.DebuggerStepThroughAttribute(),  _
     System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0"),  _
     System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced),  _
     System.ServiceModel.MessageContractAttribute(WrapperName:="findObjectsResponse", WrapperNamespace:="http://www.fedora.info/definitions/1/0/types/", IsWrapped:=true)>  _
    Partial Public Class findObjectsResponse
        
        <System.ServiceModel.MessageBodyMemberAttribute([Namespace]:="http://www.fedora.info/definitions/1/0/types/", Order:=0),  _
         System.Xml.Serialization.XmlElementAttribute(Form:=System.Xml.Schema.XmlSchemaForm.Unqualified)>  _
        Public result As ApiA.FieldSearchResult
        
        Public Sub New()
            MyBase.New
        End Sub
        
        Public Sub New(ByVal result As ApiA.FieldSearchResult)
            MyBase.New
            Me.result = result
        End Sub
    End Class
    
    <System.Diagnostics.DebuggerStepThroughAttribute(),  _
     System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0"),  _
     System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced),  _
     System.ServiceModel.MessageContractAttribute(WrapperName:="resumeFindObjects", WrapperNamespace:="http://www.fedora.info/definitions/1/0/types/", IsWrapped:=true)>  _
    Partial Public Class resumeFindObjectsRequest
        
        <System.ServiceModel.MessageBodyMemberAttribute([Namespace]:="http://www.fedora.info/definitions/1/0/types/", Order:=0),  _
         System.Xml.Serialization.XmlElementAttribute(Form:=System.Xml.Schema.XmlSchemaForm.Unqualified)>  _
        Public sessionToken As String
        
        Public Sub New()
            MyBase.New
        End Sub
        
        Public Sub New(ByVal sessionToken As String)
            MyBase.New
            Me.sessionToken = sessionToken
        End Sub
    End Class
    
    <System.Diagnostics.DebuggerStepThroughAttribute(),  _
     System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0"),  _
     System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced),  _
     System.ServiceModel.MessageContractAttribute(WrapperName:="resumeFindObjectsResponse", WrapperNamespace:="http://www.fedora.info/definitions/1/0/types/", IsWrapped:=true)>  _
    Partial Public Class resumeFindObjectsResponse
        
        <System.ServiceModel.MessageBodyMemberAttribute([Namespace]:="http://www.fedora.info/definitions/1/0/types/", Order:=0),  _
         System.Xml.Serialization.XmlElementAttribute(Form:=System.Xml.Schema.XmlSchemaForm.Unqualified)>  _
        Public result As ApiA.FieldSearchResult
        
        Public Sub New()
            MyBase.New
        End Sub
        
        Public Sub New(ByVal result As ApiA.FieldSearchResult)
            MyBase.New
            Me.result = result
        End Sub
    End Class
    
    <System.Diagnostics.DebuggerStepThroughAttribute(),  _
     System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0"),  _
     System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced),  _
     System.ServiceModel.MessageContractAttribute(WrapperName:="getObjectHistory", WrapperNamespace:="http://www.fedora.info/definitions/1/0/types/", IsWrapped:=true)>  _
    Partial Public Class getObjectHistoryRequest
        
        <System.ServiceModel.MessageBodyMemberAttribute([Namespace]:="http://www.fedora.info/definitions/1/0/types/", Order:=0),  _
         System.Xml.Serialization.XmlElementAttribute(Form:=System.Xml.Schema.XmlSchemaForm.Unqualified)>  _
        Public pid As String
        
        Public Sub New()
            MyBase.New
        End Sub
        
        Public Sub New(ByVal pid As String)
            MyBase.New
            Me.pid = pid
        End Sub
    End Class
    
    <System.Diagnostics.DebuggerStepThroughAttribute(),  _
     System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0"),  _
     System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced),  _
     System.ServiceModel.MessageContractAttribute(WrapperName:="getObjectHistoryResponse", WrapperNamespace:="http://www.fedora.info/definitions/1/0/types/", IsWrapped:=true)>  _
    Partial Public Class getObjectHistoryResponse
        
        <System.ServiceModel.MessageBodyMemberAttribute([Namespace]:="http://www.fedora.info/definitions/1/0/types/", Order:=0),  _
         System.Xml.Serialization.XmlElementAttribute("modifiedDate", Form:=System.Xml.Schema.XmlSchemaForm.Unqualified)>  _
        Public modifiedDate() As String
        
        Public Sub New()
            MyBase.New
        End Sub
        
        Public Sub New(ByVal modifiedDate() As String)
            MyBase.New
            Me.modifiedDate = modifiedDate
        End Sub
    End Class
    
    <System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")>  _
    Public Interface FedoraAPIAChannel
        Inherits ApiA.FedoraAPIA, System.ServiceModel.IClientChannel
    End Interface
    
    <System.Diagnostics.DebuggerStepThroughAttribute(),  _
     System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")>  _
    Partial Public Class FedoraAPIAClient
        Inherits System.ServiceModel.ClientBase(Of ApiA.FedoraAPIA)
        Implements ApiA.FedoraAPIA
        
        Public Sub New()
            MyBase.New
        End Sub
        
        Public Sub New(ByVal endpointConfigurationName As String)
            MyBase.New(endpointConfigurationName)
        End Sub
        
        Public Sub New(ByVal endpointConfigurationName As String, ByVal remoteAddress As String)
            MyBase.New(endpointConfigurationName, remoteAddress)
        End Sub
        
        Public Sub New(ByVal endpointConfigurationName As String, ByVal remoteAddress As System.ServiceModel.EndpointAddress)
            MyBase.New(endpointConfigurationName, remoteAddress)
        End Sub
        
        Public Sub New(ByVal binding As System.ServiceModel.Channels.Binding, ByVal remoteAddress As System.ServiceModel.EndpointAddress)
            MyBase.New(binding, remoteAddress)
        End Sub
        
        <System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)>  _
        Function ApiA_FedoraAPIA_describeRepository(ByVal request As ApiA.describeRepositoryRequest) As ApiA.describeRepositoryResponse Implements ApiA.FedoraAPIA.describeRepository
            Return MyBase.Channel.describeRepository(request)
        End Function
        
        Public Function describeRepository() As ApiA.RepositoryInfo
            Dim inValue As ApiA.describeRepositoryRequest = New ApiA.describeRepositoryRequest()
            Dim retVal As ApiA.describeRepositoryResponse = CType(Me,ApiA.FedoraAPIA).describeRepository(inValue)
            Return retVal.repositoryInfo
        End Function
        
        <System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)>  _
        Function ApiA_FedoraAPIA_getObjectProfile(ByVal request As ApiA.getObjectProfileRequest) As ApiA.getObjectProfileResponse Implements ApiA.FedoraAPIA.getObjectProfile
            Return MyBase.Channel.getObjectProfile(request)
        End Function
        
        Public Function getObjectProfile(ByVal pid As String, ByVal asOfDateTime As String) As ApiA.ObjectProfile
            Dim inValue As ApiA.getObjectProfileRequest = New ApiA.getObjectProfileRequest()
            inValue.pid = pid
            inValue.asOfDateTime = asOfDateTime
            Dim retVal As ApiA.getObjectProfileResponse = CType(Me,ApiA.FedoraAPIA).getObjectProfile(inValue)
            Return retVal.objectProfile
        End Function
        
        <System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)>  _
        Function ApiA_FedoraAPIA_listMethods(ByVal request As ApiA.listMethodsRequest) As ApiA.listMethodsResponse Implements ApiA.FedoraAPIA.listMethods
            Return MyBase.Channel.listMethods(request)
        End Function
        
        Public Function listMethods(ByVal pid As String, ByVal asOfDateTime As String) As ApiA.ObjectMethodsDef()
            Dim inValue As ApiA.listMethodsRequest = New ApiA.listMethodsRequest()
            inValue.pid = pid
            inValue.asOfDateTime = asOfDateTime
            Dim retVal As ApiA.listMethodsResponse = CType(Me,ApiA.FedoraAPIA).listMethods(inValue)
            Return retVal.objectMethod
        End Function
        
        <System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)>  _
        Function ApiA_FedoraAPIA_listDatastreams(ByVal request As ApiA.listDatastreamsRequest) As ApiA.listDatastreamsResponse Implements ApiA.FedoraAPIA.listDatastreams
            Return MyBase.Channel.listDatastreams(request)
        End Function
        
        Public Function listDatastreams(ByVal pid As String, ByVal asOfDateTime As String) As ApiA.DatastreamDef()
            Dim inValue As ApiA.listDatastreamsRequest = New ApiA.listDatastreamsRequest()
            inValue.pid = pid
            inValue.asOfDateTime = asOfDateTime
            Dim retVal As ApiA.listDatastreamsResponse = CType(Me,ApiA.FedoraAPIA).listDatastreams(inValue)
            Return retVal.datastreamDef
        End Function
        
        <System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)>  _
        Function ApiA_FedoraAPIA_getDatastreamDissemination(ByVal request As ApiA.getDatastreamDisseminationRequest) As ApiA.getDatastreamDisseminationResponse Implements ApiA.FedoraAPIA.getDatastreamDissemination
            Return MyBase.Channel.getDatastreamDissemination(request)
        End Function
        
        Public Function getDatastreamDissemination(ByVal pid As String, ByVal dsID As String, ByVal asOfDateTime As String) As ApiA.MIMETypedStream
            Dim inValue As ApiA.getDatastreamDisseminationRequest = New ApiA.getDatastreamDisseminationRequest()
            inValue.pid = pid
            inValue.dsID = dsID
            inValue.asOfDateTime = asOfDateTime
            Dim retVal As ApiA.getDatastreamDisseminationResponse = CType(Me,ApiA.FedoraAPIA).getDatastreamDissemination(inValue)
            Return retVal.dissemination
        End Function
        
        <System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)>  _
        Function ApiA_FedoraAPIA_getDissemination(ByVal request As ApiA.getDisseminationRequest) As ApiA.getDisseminationResponse Implements ApiA.FedoraAPIA.getDissemination
            Return MyBase.Channel.getDissemination(request)
        End Function
        
        Public Function getDissemination(ByVal pid As String, ByVal serviceDefinitionPid As String, ByVal methodName As String, ByVal parameters() As ApiA.[Property], ByVal asOfDateTime As String) As ApiA.MIMETypedStream
            Dim inValue As ApiA.getDisseminationRequest = New ApiA.getDisseminationRequest()
            inValue.pid = pid
            inValue.serviceDefinitionPid = serviceDefinitionPid
            inValue.methodName = methodName
            inValue.parameters = parameters
            inValue.asOfDateTime = asOfDateTime
            Dim retVal As ApiA.getDisseminationResponse = CType(Me,ApiA.FedoraAPIA).getDissemination(inValue)
            Return retVal.dissemination
        End Function
        
        <System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)>  _
        Function ApiA_FedoraAPIA_findObjects(ByVal request As ApiA.findObjectsRequest) As ApiA.findObjectsResponse Implements ApiA.FedoraAPIA.findObjects
            Return MyBase.Channel.findObjects(request)
        End Function
        
        Public Function findObjects(ByVal resultFields() As String, ByVal maxResults As String, ByVal query As ApiA.FieldSearchQuery) As ApiA.FieldSearchResult
            Dim inValue As ApiA.findObjectsRequest = New ApiA.findObjectsRequest()
            inValue.resultFields = resultFields
            inValue.maxResults = maxResults
            inValue.query = query
            Dim retVal As ApiA.findObjectsResponse = CType(Me,ApiA.FedoraAPIA).findObjects(inValue)
            Return retVal.result
        End Function
        
        <System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)>  _
        Function ApiA_FedoraAPIA_resumeFindObjects(ByVal request As ApiA.resumeFindObjectsRequest) As ApiA.resumeFindObjectsResponse Implements ApiA.FedoraAPIA.resumeFindObjects
            Return MyBase.Channel.resumeFindObjects(request)
        End Function
        
        Public Function resumeFindObjects(ByVal sessionToken As String) As ApiA.FieldSearchResult
            Dim inValue As ApiA.resumeFindObjectsRequest = New ApiA.resumeFindObjectsRequest()
            inValue.sessionToken = sessionToken
            Dim retVal As ApiA.resumeFindObjectsResponse = CType(Me,ApiA.FedoraAPIA).resumeFindObjects(inValue)
            Return retVal.result
        End Function
        
        <System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)>  _
        Function ApiA_FedoraAPIA_getObjectHistory(ByVal request As ApiA.getObjectHistoryRequest) As ApiA.getObjectHistoryResponse Implements ApiA.FedoraAPIA.getObjectHistory
            Return MyBase.Channel.getObjectHistory(request)
        End Function
        
        Public Function getObjectHistory(ByVal pid As String) As String()
            Dim inValue As ApiA.getObjectHistoryRequest = New ApiA.getObjectHistoryRequest()
            inValue.pid = pid
            Dim retVal As ApiA.getObjectHistoryResponse = CType(Me,ApiA.FedoraAPIA).getObjectHistory(inValue)
            Return retVal.modifiedDate
        End Function
    End Class
End Namespace
